export const FIELD_TYPES: { [key: string]: any } = {
  text: {
    type: 'text',
    name: 'form.field.name.singleLineText',
    description: 'form.field.description.text',
    fieldOptions: {},
    icon: 'FIELD_TEXT',
  },
  number: {
    type: 'number',
    name: 'form.field.name.number',
    description: '',
    fieldOptions: { precision: 1 },
    icon: 'FIELD_NUMBER',
    formatOptions: [
      { name: 'form.field.option.decimal', value: 'decimal' },
      { name: 'form.field.option.integer', value: 'integer' },
    ],
    precisionOptions: [
      { name: '1.0', value: 1 },
      { name: '1.00', value: 2 },
      { name: '1.000', value: 3 },
      { name: '1.0000', value: 4 },
      { name: '1.00000', value: 5 },
      { name: '1.000000', value: 6 },
      { name: '1.0000000', value: 7 },
      { name: '1.00000000', value: 8 },
    ],
  },
  reference: {
    type: 'reference',
    name: 'form.field.name.recordReference',
    description: '',
    fieldOptions: {},
    icon: 'FIELD_REFERENCE',
  },
  tableReference: {
    name: 'form.field.name.tableReference',
    type: 'tableReference',
    description: '',
    fieldOptions: {},
    icon: 'FIELD_TABLE_REFERENCE',
  },
  multipleAttachment: {
    type: 'multipleAttachment',
    name: 'form.field.name.attachment',
    description: 'form.field.description.attachment',
    fieldOptions: {},
    icon: 'FIELD_ATTACHMENT',
  },
  multilineText: {
    name: 'form.field.name.longText',
    type: 'multilineText',
    description: 'form.field.description.longText',
    fieldOptions: {},
    icon: 'FIELD_LONGTEXT',
  },
  select: {
    name: 'form.field.name.singleSelect',
    type: 'select',
    description: 'form.field.description.singleSelect',
    fieldOptions: { choiceOrder: [], choices: {} },
    icon: 'FIELD_SELECT',
  },
  multiSelect: {
    name: 'form.field.name.multiSelect',
    type: 'multiSelect',
    description: 'form.field.description.multiSelect',
    fieldOptions: { choiceOrder: [], choices: {} },
    icon: 'FIELD_MULTISELECT',
  },
  formula: {
    name: 'form.field.name.formula',
    type: 'formula',
    description: 'form.field.description.formula',
    icon: 'FIELD_FORMULA',
    fieldOptions: { referencedColumnIdsForValue: [], formulaTextParsed: '' },
    functions: [
      { name: 'AVERAGE()', type: 'function', value: 'AVERAGE()' },
      { name: 'COUNT()', type: 'function', value: 'COUNT()' },
      { name: 'COUNTA()', type: 'function', value: 'COUNTA()' },
      { name: 'SUM()', type: 'function', value: 'SUM()' },
      { name: 'MIN()', type: 'function', value: 'MIN()' },
      { name: 'MAX()', type: 'function', value: 'MAX()' },
      { name: 'AND()', type: 'function', value: 'AND()' },
      { name: 'OR()', type: 'function', value: 'OR()' },
    ],
    formatOptions: [
      { name: 'field.modal.fieldOptions.format.decimal', value: 'decimal' },
      { name: 'field.modal.fieldOptions.format.integer', value: 'integer' },
      { name: 'field.modal.fieldOptions.format.percent', value: 'percent' },
      { name: 'field.modal.fieldOptions.format.duration', value: 'duration' },
    ],
    decimal: [
      { name: '1.0', value: 1 },
      { name: '1.00', value: 2 },
      { name: '1.000', value: 3 },
      { name: '1.0000', value: 4 },
      { name: '1.00000', value: 5 },
      { name: '1.000000', value: 6 },
      { name: '1.0000000', value: 7 },
      { name: '1.00000000', value: 8 },
    ],
    percent: [
      { name: '1%', value: 0 },
      { name: '1.0%', value: 1 },
      { name: '1.00%', value: 2 },
      { name: '1.000%', value: 3 },
      { name: '1.0000%', value: 4 },
      { name: '1.00000%', value: 5 },
      { name: '1.000000%', value: 6 },
      { name: '1.0000000%', value: 7 },
      { name: '1.00000000%', value: 8 },
    ],
    duration: [
      { name: 'h:mm(e.g. 1:23)', value: 'h:mm' },
      { name: 'h:mm:ss(e.g. 3:45, 1.23:40)', value: 'h:mm:ss' },
      { name: 'h:mm:ss.s(e.g. 3:45.6, 1.23:40.0)', value: 'h:mm:ss.s' },
      { name: 'h:mm:ss.ss(e.g. 3.45.67, 1.23:40.00)', value: 'h:mm:ss.ss' },
      { name: 'h:mm:ss.sss(e.g. 3.45.678, 1.23:40.000)', value: 'h:mm:ss.sss' },
    ],
  },
  collaborator: {
    name: 'form.field.name.collaborator',
    type: 'collaborator',
    description: 'form.field.description.collaborator',
    icon: 'FIELD_COLLABORATOR',
    fieldOptions: { multiCollaborator: true, shouldNotify: true },
  },
  date: {
    name: 'form.field.name.date',
    type: 'date',
    description: 'form.field.description.date',
    icon: 'FIELD_DATE',
    fieldOptions: { dateFormat: 'Local', isDateTime: false },
    dateFormatOptions: [
      { name: 'form.field.option.local', value: 'Local' },
      { name: 'form.field.option.friendly', value: 'Friendly' },
      { name: 'form.field.option.us', value: 'US' },
      { name: 'form.field.option.european', value: 'European' },
      { name: 'form.field.option.iso', value: 'ISO' },
    ],
    timeFormatOptions: [
      { name: 'form.field.option.12hour', value: '12hour' },
      { name: 'form.field.option.24hour', value: '24hour' },
    ],
  },
};
