
import { IChartData } from '.';

export const FakeData: IChartData[] = [
    {
        "key": "1",
        "type": 'BAR',
        "name": 'Bar Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Raff", "value": 106, "color": "#be7ca6" },
        { "label": "Pia", "value": 469, "color": "#eae17b" },
        { "label": "Dore", "value": 221, "color": "#6ad6aa" },
        { "label": "Gunar", "value": 156, "color": "#42119b" },
        { "label": "Adara", "value": 279, "color": "#84efe9" },
        { "label": "Anatol", "value": 223, "color": "#49ef58" },
        { "label": "Christina", "value": 368, "color": "#70fbb5" },
        { "label": "Bernadette", "value": 472, "color": "#c7eaa1" },
        { "label": "Kelsi", "value": 399, "color": "#94d23a" },
        { "label": "Allison", "value": 292, "color": "#cb54dc" },
        { "label": "Jud", "value": 52, "color": "#ae3f2e" },
        { "label": "Bennett", "value": 128, "color": "#3bb91c" },
        { "label": "Ivar", "value": 340, "color": "#d8f1d3" },
        { "label": "Nial", "value": 89, "color": "#25bc4a" },
        { "label": "Olimpia", "value": 107, "color": "#b5b2e8" },
        { "label": "Kristel", "value": 187, "color": "#7b44f3" },
        { "label": "Cara", "value": 372, "color": "#4ccbb7" },
        { "label": "Noel", "value": 449, "color": "#104f26" },
        { "label": "Ileane", "value": 354, "color": "#73746a" },
        { "label": "Jany", "value": 224, "color": "#d7d215" }]
    }, {
        "key": "2",
        "type": 'PIE',
        "name": 'Pie Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Raff", "value": 106, "color": "#be7ca6" },
        { "label": "Pia", "value": 469, "color": "#eae17b" },
        { "label": "Dore", "value": 221, "color": "#6ad6aa" },
        { "label": "Gunar", "value": 156, "color": "#42119b" },
        { "label": "Adara", "value": 279, "color": "#84efe9" },
        { "label": "Anatol", "value": 223, "color": "#49ef58" },
        { "label": "Christina", "value": 368, "color": "#70fbb5" },
        { "label": "Bernadette", "value": 472, "color": "#c7eaa1" },
        { "label": "Kelsi", "value": 399, "color": "#94d23a" },
        { "label": "Allison", "value": 292, "color": "#cb54dc" },
        { "label": "Jud", "value": 52, "color": "#ae3f2e" },
        { "label": "Bennett", "value": 128, "color": "#3bb91c" },
        { "label": "Ivar", "value": 340, "color": "#d8f1d3" },
        { "label": "Nial", "value": 89, "color": "#25bc4a" },
        { "label": "Olimpia", "value": 107, "color": "#b5b2e8" },
        { "label": "Kristel", "value": 187, "color": "#7b44f3" },
        { "label": "Cara", "value": 372, "color": "#4ccbb7" },
        { "label": "Noel", "value": 449, "color": "#104f26" },
        { "label": "Ileane", "value": 354, "color": "#73746a" },
        { "label": "Jany", "value": 224, "color": "#d7d215" }]
    }, {
        "key": "3",
        "type": 'LINE',
        "name": 'Line Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Raff", "value": 106, "color": "#be7ca6" },
        { "label": "Pia", "value": 469, "color": "#eae17b" },
        { "label": "Dore", "value": 221, "color": "#6ad6aa" },
        { "label": "Gunar", "value": 156, "color": "#42119b" },
        { "label": "Adara", "value": 279, "color": "#84efe9" },
        { "label": "Anatol", "value": 223, "color": "#49ef58" },
        { "label": "Christina", "value": 368, "color": "#70fbb5" },
        { "label": "Bernadette", "value": 472, "color": "#c7eaa1" },
        { "label": "Kelsi", "value": 399, "color": "#94d23a" },
        { "label": "Allison", "value": 292, "color": "#cb54dc" },
        { "label": "Jud", "value": 52, "color": "#ae3f2e" },
        { "label": "Bennett", "value": 128, "color": "#3bb91c" },
        { "label": "Ivar", "value": 340, "color": "#d8f1d3" },
        { "label": "Nial", "value": 89, "color": "#25bc4a" },
        { "label": "Olimpia", "value": 107, "color": "#b5b2e8" },
        { "label": "Kristel", "value": 187, "color": "#7b44f3" },
        { "label": "Cara", "value": 372, "color": "#4ccbb7" },
        { "label": "Noel", "value": 449, "color": "#104f26" },
        { "label": "Ileane", "value": 354, "color": "#73746a" },
        { "label": "Jany", "value": 224, "color": "#d7d215" }]
    },
    {
        "key": "4",
        "type": 'BAR',
        "name": 'Bar Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Raff", "value": 106, "color": "#be7ca6" },
        { "label": "Pia", "value": 469, "color": "#eae17b" },
        { "label": "Dore", "value": 221, "color": "#6ad6aa" },
        { "label": "Gunar", "value": 156, "color": "#42119b" },
        { "label": "Adara", "value": 279, "color": "#84efe9" },
        { "label": "Anatol", "value": 223, "color": "#49ef58" },
        { "label": "Christina", "value": 368, "color": "#70fbb5" },
        { "label": "Bernadette", "value": 472, "color": "#c7eaa1" },
        { "label": "Kelsi", "value": 399, "color": "#94d23a" },
        { "label": "Allison", "value": 292, "color": "#cb54dc" },
        { "label": "Jud", "value": 52, "color": "#ae3f2e" },
        { "label": "Bennett", "value": 128, "color": "#3bb91c" },
        { "label": "Ivar", "value": 340, "color": "#d8f1d3" },
        { "label": "Nial", "value": 89, "color": "#25bc4a" },
        { "label": "Olimpia", "value": 107, "color": "#b5b2e8" },
        { "label": "Kristel", "value": 187, "color": "#7b44f3" },
        { "label": "Cara", "value": 372, "color": "#4ccbb7" },
        { "label": "Noel", "value": 449, "color": "#104f26" },
        { "label": "Ileane", "value": 354, "color": "#73746a" },
        { "label": "Jany", "value": 224, "color": "#d7d215" }]
    }, {
        "key": "5",
        "type": 'PIE',
        "name": 'Pie Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Raff", "value": 106, "color": "#be7ca6" },
        { "label": "Pia", "value": 469, "color": "#eae17b" },
        { "label": "Dore", "value": 221, "color": "#6ad6aa" },
        { "label": "Gunar", "value": 156, "color": "#42119b" },
        { "label": "Adara", "value": 279, "color": "#84efe9" },
        { "label": "Anatol", "value": 223, "color": "#49ef58" },
        { "label": "Christina", "value": 368, "color": "#70fbb5" },
        { "label": "Bernadette", "value": 472, "color": "#c7eaa1" },
        { "label": "Kelsi", "value": 399, "color": "#94d23a" },
        { "label": "Allison", "value": 292, "color": "#cb54dc" },
        { "label": "Jud", "value": 52, "color": "#ae3f2e" },
        { "label": "Bennett", "value": 128, "color": "#3bb91c" },
        { "label": "Ivar", "value": 340, "color": "#d8f1d3" },
        { "label": "Nial", "value": 89, "color": "#25bc4a" },
        { "label": "Olimpia", "value": 107, "color": "#b5b2e8" },
        { "label": "Kristel", "value": 187, "color": "#7b44f3" },
        { "label": "Cara", "value": 372, "color": "#4ccbb7" },
        { "label": "Noel", "value": 449, "color": "#104f26" },
        { "label": "Ileane", "value": 354, "color": "#73746a" },
        { "label": "Jany", "value": 224, "color": "#d7d215" }]
    }, {
        "key": "6",
        "type": 'LINE',
        "name": 'Line Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Raff", "value": 106, "color": "#be7ca6" },
        { "label": "Pia", "value": 469, "color": "#eae17b" },
        { "label": "Dore", "value": 221, "color": "#6ad6aa" },
        { "label": "Gunar", "value": 156, "color": "#42119b" },
        { "label": "Adara", "value": 279, "color": "#84efe9" },
        { "label": "Anatol", "value": 223, "color": "#49ef58" },
        { "label": "Christina", "value": 368, "color": "#70fbb5" },
        { "label": "Bernadette", "value": 472, "color": "#c7eaa1" },
        { "label": "Kelsi", "value": 399, "color": "#94d23a" },
        { "label": "Allison", "value": 292, "color": "#cb54dc" },
        { "label": "Jud", "value": 52, "color": "#ae3f2e" },
        { "label": "Bennett", "value": 128, "color": "#3bb91c" },
        { "label": "Ivar", "value": 340, "color": "#d8f1d3" },
        { "label": "Nial", "value": 89, "color": "#25bc4a" },
        { "label": "Olimpia", "value": 107, "color": "#b5b2e8" },
        { "label": "Kristel", "value": 187, "color": "#7b44f3" },
        { "label": "Cara", "value": 372, "color": "#4ccbb7" },
        { "label": "Noel", "value": 449, "color": "#104f26" },
        { "label": "Ileane", "value": 354, "color": "#73746a" },
        { "label": "Jany", "value": 224, "color": "#d7d215" }]
    },
    {
        "key": "7",
        "type": 'BAR',
        "name": 'Bar Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Raff", "value": 106, "color": "#be7ca6" },
        { "label": "Pia", "value": 469, "color": "#eae17b" },
        { "label": "Dore", "value": 221, "color": "#6ad6aa" },
        { "label": "Gunar", "value": 156, "color": "#42119b" },
        { "label": "Adara", "value": 279, "color": "#84efe9" },
        { "label": "Anatol", "value": 223, "color": "#49ef58" },
        { "label": "Christina", "value": 368, "color": "#70fbb5" },
        { "label": "Bernadette", "value": 472, "color": "#c7eaa1" },
        { "label": "Kelsi", "value": 399, "color": "#94d23a" },
        { "label": "Allison", "value": 292, "color": "#cb54dc" },
        { "label": "Jud", "value": 52, "color": "#ae3f2e" },
        { "label": "Bennett", "value": 128, "color": "#3bb91c" },
        { "label": "Ivar", "value": 340, "color": "#d8f1d3" },
        { "label": "Nial", "value": 89, "color": "#25bc4a" },
        { "label": "Olimpia", "value": 107, "color": "#b5b2e8" },
        { "label": "Kristel", "value": 187, "color": "#7b44f3" },
        { "label": "Cara", "value": 372, "color": "#4ccbb7" },
        { "label": "Noel", "value": 449, "color": "#104f26" },
        { "label": "Ileane", "value": 354, "color": "#73746a" },
        { "label": "Jany", "value": 224, "color": "#d7d215" }]
    }, {
        "key": "8",
        "type": 'PIE',
        "name": 'Pie Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Raff", "value": 106, "color": "#be7ca6" },
        { "label": "Pia", "value": 469, "color": "#eae17b" },
        { "label": "Dore", "value": 221, "color": "#6ad6aa" },
        { "label": "Gunar", "value": 156, "color": "#42119b" },
        { "label": "Adara", "value": 279, "color": "#84efe9" },
        { "label": "Anatol", "value": 223, "color": "#49ef58" },
        { "label": "Christina", "value": 368, "color": "#70fbb5" },
        { "label": "Bernadette", "value": 472, "color": "#c7eaa1" },
        { "label": "Kelsi", "value": 399, "color": "#94d23a" },
        { "label": "Allison", "value": 292, "color": "#cb54dc" },
        { "label": "Jud", "value": 52, "color": "#ae3f2e" },
        { "label": "Bennett", "value": 128, "color": "#3bb91c" },
        { "label": "Ivar", "value": 340, "color": "#d8f1d3" },
        { "label": "Nial", "value": 89, "color": "#25bc4a" },
        { "label": "Olimpia", "value": 107, "color": "#b5b2e8" },
        { "label": "Kristel", "value": 187, "color": "#7b44f3" },
        { "label": "Cara", "value": 372, "color": "#4ccbb7" },
        { "label": "Noel", "value": 449, "color": "#104f26" },
        { "label": "Ileane", "value": 354, "color": "#73746a" },
        { "label": "Jany", "value": 224, "color": "#d7d215" }]
    }
];
