
import { IChartData } from '.';

export const FakeData15: IChartData[] = [
    {
        "type": 'BAR',
        "name": 'Bar Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Celine", "value": 176, "color": "#7a9b19" },
        { "label": "Margalit", "value": 59, "color": "#6e9e7f" },
        { "label": "Diannne", "value": 163, "color": "#717432" },
        { "label": "Benjy", "value": 104, "color": "#85a0aa" },
        { "label": "Helli", "value": 251, "color": "#73a836" },
        { "label": "Swen", "value": 31, "color": "#9b5b69" },
        { "label": "Cory", "value": 58, "color": "#daed09" },
        { "label": "Bordie", "value": 200, "color": "#664701" },
        { "label": "Cathee", "value": 269, "color": "#e9e5e7" },
        { "label": "Karney", "value": 391, "color": "#95d78d" },
        { "label": "Hirsch", "value": 378, "color": "#e4e1d7" },
        { "label": "Francklyn", "value": 387, "color": "#1b09d3" },
        { "label": "Hyacinthia", "value": 84, "color": "#352b88" },
        { "label": "Bordie", "value": 200, "color": "#664701" },
        { "label": "Cathee", "value": 269, "color": "#e9e5e7" },
        { "label": "Karney", "value": 391, "color": "#95d78d" },
        { "label": "Hirsch", "value": 378, "color": "#e4e1d7" },
        { "label": "Bordie", "value": 200, "color": "#664701" },
        { "label": "Cathee", "value": 269, "color": "#e9e5e7" },
        { "label": "Karney", "value": 391, "color": "#95d78d" },
        { "label": "Hirsch", "value": 378, "color": "#e4e1d7" },
        { "label": "Bordie", "value": 200, "color": "#664701" },
        { "label": "Cathee", "value": 269, "color": "#e9e5e7" },
        { "label": "Karney", "value": 391, "color": "#95d78d" },
        { "label": "Levey", "value": 186, "color": "#34f43e" },
        { "label": "Thayne", "value": 63, "color": "#5b4f2c" }]
    }, {
        "type": 'PIE',
        "name": 'Pie Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Celine", "value": 176, "color": "#7a9b19" },
        { "label": "Margalit", "value": 59, "color": "#6e9e7f" },
        { "label": "Diannne", "value": 163, "color": "#717432" },
        { "label": "Benjy", "value": 104, "color": "#85a0aa" },
        { "label": "Helli", "value": 251, "color": "#73a836" },
        { "label": "Swen", "value": 31, "color": "#9b5b69" },
        { "label": "Cory", "value": 58, "color": "#daed09" },
        { "label": "Bordie", "value": 200, "color": "#664701" },
        { "label": "Cathee", "value": 269, "color": "#e9e5e7" },
        { "label": "Karney", "value": 391, "color": "#95d78d" },
        { "label": "Hirsch", "value": 378, "color": "#e4e1d7" },
        { "label": "Francklyn", "value": 387, "color": "#1b09d3" },
        { "label": "Hyacinthia", "value": 84, "color": "#352b88" },
        { "label": "Levey", "value": 186, "color": "#34f43e" },
        { "label": "Thayne", "value": 63, "color": "#5b4f2c" }]
    }, {
        "type": 'LINE',
        "name": 'Line Chart',
        "XAxis": "Revenue",
        "YAxis": "Sum Profit",
        "values": [{ "label": "Celine", "value": 176, "color": "#7a9b19" },
        { "label": "Margalit", "value": 59, "color": "#6e9e7f" },
        { "label": "Diannne", "value": 163, "color": "#717432" },
        { "label": "Benjy", "value": 104, "color": "#85a0aa" },
        { "label": "Helli", "value": 251, "color": "#73a836" },
        { "label": "Swen", "value": 31, "color": "#9b5b69" },
        { "label": "Cory", "value": 58, "color": "#daed09" },
        { "label": "Bordie", "value": 200, "color": "#664701" },
        { "label": "Cathee", "value": 269, "color": "#e9e5e7" },
        { "label": "Karney", "value": 391, "color": "#95d78d" },
        { "label": "Hirsch", "value": 378, "color": "#e4e1d7" },
        { "label": "Bordie", "value": 200, "color": "#664701" },
        { "label": "Cathee", "value": 269, "color": "#e9e5e7" },
        { "label": "Karney", "value": 391, "color": "#95d78d" },
        { "label": "Hirsch", "value": 378, "color": "#e4e1d7" },
        { "label": "Bordie", "value": 200, "color": "#664701" },
        { "label": "Cathee", "value": 269, "color": "#e9e5e7" },
        { "label": "Karney", "value": 391, "color": "#95d78d" },
        { "label": "Hirsch", "value": 378, "color": "#e4e1d7" },
        { "label": "Francklyn", "value": 387, "color": "#1b09d3" },
        { "label": "Hyacinthia", "value": 84, "color": "#352b88" },
        { "label": "Levey", "value": 186, "color": "#34f43e" },
        { "label": "Thayne", "value": 63, "color": "#5b4f2c" }]
    }
];
